services:
  - type: web
    name: auction-backend-l24v
    env: go
    rootDir: backend
    buildCommand: go build -o cricket-auction .
    startCommand: ./cricket-auction
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: "8080"
      - key: MONGODB_URI
        sync: false
      - key: MONGODB_DATABASE
        value: cricket_auction
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false

  - type: web
    name: cricketive-auction
    env: static
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    healthCheckPath: /
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_BASE_URL
        value: https://cricket-auction-public.onrender.com
      - key: NODE_VERSION
        value: "18"